#!/bin/bash
# Test scenario script - runs test scenario and generates artifacts
# This file is shared from host to worker container via /work mount

set -e

SCENARIO_ID="${SCENARIO_ID:-1}"
DURATION="${SCENARIO_DURATION:-60}"

echo "[Worker] Starting scenario $SCENARIO_ID (duration: ${DURATION}s)"

# Determine artifact location: use mounted artifacts dir if available, else /tmp
if [ -n "$WORKER_ARTIFACTS_DIR" ]; then
    ARTIFACT_DIR="${WORKER_ARTIFACTS_DIR}/test_scenario_${SCENARIO_ID}"
else
    ARTIFACT_DIR="/tmp/scenario_${SCENARIO_ID}"
fi
mkdir -p "$ARTIFACT_DIR"

# Create test artifact files
echo "Test artifact generated by scenario $SCENARIO_ID at $(date)" > "${ARTIFACT_DIR}/test_artifact.txt"
echo "Screenshot captured for scenario $SCENARIO_ID" > "${ARTIFACT_DIR}/screenshot.png"
echo "Log file for scenario $SCENARIO_ID" > "${ARTIFACT_DIR}/test_log.log"

# Create nested directory
mkdir -p "${ARTIFACT_DIR}/nested/dir"
echo "Nested artifact for scenario $SCENARIO_ID" > "${ARTIFACT_DIR}/nested/dir/data.txt"

# Simulate test work
sleep "$DURATION"

echo "[Worker] Scenario $SCENARIO_ID completed in ${DURATION}s"

# List created artifacts
echo "[Worker] Artifacts created:"
ls -la "$ARTIFACT_DIR/" || true
ls -la "${ARTIFACT_DIR}/nested/dir/" || true

echo "RESULT:scenario=$SCENARIO_ID:status=passed:duration=${DURATION}s"

exit 0